# UNCOVERS HAPLOTYPES IN BACTERIAL CONTIGS USING LENS
# Input files: ../asm/contigs.fasta, LONG_READ_FASTQ
# Output files: haplotypes.txt

#------------------------------------------------------------------------------
# High-level commands

all:
	make -C align
	make -C detect

clean:
	make -C align clean
	make -C detect clean
