# UNCOVERS HAPLOTYPES IN BACTERIAL CONTIGS USING LENS
# Input files: CTGS, CONTIG_CLASSIFICATION, TAXONOMIC_CLASSIFICATION
# Output files: taxa.abundances

#------------------------------------------------------------------------------
# High-level commands

all:
	make -C align
	make -C detect

clean:
	make -C align clean
	make -C detect clean
